### ISSUE TITLE
Consulta xHacking

### ISSUE THREAD

**Issue by ass87** [gpascualg/xHacking#1]
Que tal Guillem? Yo te escribí un mail hace unos días desde Argentina para hacerte algunas consultas, y me pediste que las hiciera por acá.
Antes que nada, decir que soy principante a tope con estas cosas, por favor, paciencia xD

El tema es el siguiente:
Como te comentaba en el mail, existe un control sobre las clases trabajadoras, las cuales poseen un macro incorporado para minar, pescar, talar. Para que este macro no sea desatendido, implementaron lo que llaman "centinela" que no es mas que un script que te pide ingresar un codigo numérico aleatorio.

Mi idea, viendo tus videos, fue interceptar ese paquete con el codigo númerico y, mediante un detour, mandar el paquete de respuesta.
El problema se me presenta en que los paquetes estan encriptados; cuando uso la implementacion del recv para leer lo único que consigo son strings ilegibles; por lo tanto hasta ahí llegué xD
Existirá dentro de la librería alguna función para saltear este encriptado? 

Muchas gracias.
Saludos, Pedro.

**Comment by gpascualg** [comment]
No existen funciones para eso, ya que el método de encriptación pueden ser muchos y sería muy difícil automatizar tal proceso.

Entiendo que usas WPE pro para interceptar los paquetes? Prueba a hacer un detour en el recv y ver que resultados obtienes. Lo primero que prodrías probar es si la encriptación es la llamada "Cesar".

Figúrate que tenemos la string "abcd", si usamos:
César 1: `bcde`
César 2: `cdef`

Básicamente, césar se basa en sumar X a una letra para obtener otra. Para obtener el original solo hay que restar esta misma X. Mírate por ejemplo: http://programeveryday.com/post/implementing-a-basic-caesar-cipher-in-python/

Si no se trata de esto, lo único que te puedo recomendar es:
1. Entiendo que el número de lo muestran en algun lado? Usa cheat engine para encontrar la dirección de memoria del número cuando lo muestra, y así siempre lo tendrás. Generalmente, habrá otra variable true/false cercana a esta que te podría servir para saber cuando te piden  y cuando no.
2. Usar OllyDbg para ver como está implementado su recv. Si hay algún tipo de encriptación, prácticamente seguro que está ahí. A veces usar PEiD va bien, puede indicar donde hay encriptaciones y de que tipo.

Suerte!

**Comment by ass87** [comment]
Gracias por la respuesta!
La captura de los paquetes lo hice tanto con el WPE pro como con el detour en el recv; ambos me devuelven cosas ilegibles;

Voy a probar la encriptación "Cesar" a ver que pasa; con respecto al Cheat Engine, entiendo que tiene un sistema de anticheat que lo bloquea, de todas formas voy a usar el OllyDbg para chequear esto, además de ver como está implementado el recv.

Muchas gracias otra vez!
Saludos.
