### ISSUE TITLE
'api': undeclared identifier & left of '->AutoFakeWithinModule' must point to class/struct/union/generic type

### ISSUE THREAD

**Issue by AxDSan** [gpascualg/xHacking#2]
El primer error sale de la linea https://github.com/gpascualg/xHacking/blob/master/examples/CONSOLE_api.cpp#L35 yace su error en https://github.com/gpascualg/xHacking/blob/master/include/xhacking/API/API.h#L242 Me imagino por 'typo' en vez de "_api' dice "api" ahora el segundo error (yace en la linea 242 tambien) me tiene un poco medio vagabundo, resulta que no se como arreglarlo que apunte a una clase/struct/etc, etc...?

**Comment by gpascualg** [comment]
En https://github.com/gpascualg/xHacking/blob/master/examples/CONSOLE_api.cpp#L35 no hay error, y el otro (https://github.com/gpascualg/xHacking/blob/master/include/xhacking/API/API.h#L242) que remarcas, creo que sobra el "api->".

Lo que no entiendo es porque a mi me compilaba bien de entrada :/

Prueba ahora con el commit: https://github.com/gpascualg/xHacking/commit/c3133c5c25d148c5ee87072b50bf30f6eca5c8f4

**Comment by gpascualg** [comment]
Lo doy por cerrado! Si siguiera dando problemas comentalo y lo miramos
