### ISSUE TITLE
WSARecv desde WS2_32.dll

### ISSUE THREAD

**Issue by thefantas** [gpascualg/xHacking#3]
Hola.

Tengo activado:
```
	recvDetour->Wait("WSOCK32.dll", "recv", (BYTE*)nuestro_recv); //<--Ok
	recvDetour->Wait("WS2_32.dll", "recv", (BYTE*)nuestro_recv); //< --Ok
        recvDetour->Wait("WS2_32.dll", "WSARecv", (BYTE*)nuestro_recv);  <-- Provoca error
```
Y recibo los paquetes correctamente, pero al añadir otro hook devuelve un error y se cierra.
¿Será que no está implementado WSA? (aunque lo mismo ocurre con recvfrom.

`Run-Time Check Failyre #0 - The value of ESP was not property saved across a function call.`

Saludos.

**Comment by ghost** [comment]
Esto desactualizado, ya no sirve esto.

**Comment by cristiandsk** [comment]
La estructura de WSARecv es muy diferente a la de recv, tienes que hacer una función nueva

**Comment by gpascualg** [comment]
Tendrias que mirar con algun debugger/disassembler que instrucciones hay en la direccion donde se hace el detour, es probable que en nuevas updates de windows haya cambiado algo, con lo que el detour puede tener un 'length' incorrecto. 
En cualquier caso, no parece ser un problema de la libreria.

PD: La libreria no hace inspeccion del punto de detour para determinar el length, requiere que sea correcto. Tienes una alternativa mas moderna (y no acabada) en: https://github.com/APE-EDX
Te puede interesar la DLL y su codigo para hacer detours.

**Comment by thefantas** [comment]
Muchas gracias, voy a investigar esa dll.

**Comment by gpascualg** [comment]
He revisado un poco todos los repos de esa organizacion, lo que te interesa esta aqui:
https://github.com/APE-EDX/APECore

Y, mas concretamente, esta parte
https://github.com/APE-EDX/APECore/blob/master/src/redirect.cpp#L172
es en la que utilizo la libreria Capstone para saber que instrucciones hay en una address y sacar el length automaticamente.

Entre otras cosas veras que el asm esta mas explicito (llamando funciones con el nombre de la instruccion asm), asi que el codigo es bastante distinto al de xHacking. Aunque, si se adaptara, podrian hacer lo mismo.

PD: Ape esta 100% implementado para x86, y en x64 funciona hasta cierto punto
