### ISSUE TITLE
Detour

### ISSUE THREAD

**Issue by Nucito** [gpascualg/xHacking#4]
'bind1st': is not a member of 'std'
'ptr_fun': is not a member of 'std'

i use the last version in github :/

**Comment by gpascualg** [comment]
This library is no longer maintained, which means some features might not be up to date with the latest C++ standards.
For instance, if you check both

https://en.cppreference.com/w/cpp/utility/functional/bind12
https://en.cppreference.com/w/cpp/utility/functional/ptr_fun

You will see that they got deprecated in C++11 and later removed in C++17. Make sure you are compiling in, at most, C++11 to get the library to build. If you still have problems, you might want to try including <functional> (ie. `#include <functional>`).

Porting the library to C++17 (or 20) wouldn't be much work, for example by using lambdas. Sadly, I don't have the time to do so at the moment.
